FROM public.ecr.aws/lambda/python:3.7

RUN yum install -y git

COPY requirements.txt  .
RUN  pip3 install -r requirements.txt --target "${LAMBDA_TASK_ROOT}"

COPY main.py ${LAMBDA_TASK_ROOT}

CMD ["main.lambda_handler"] 